version: "3"
services:
    api:
        image: gerenciador
        build:
            context: .
        command: sh -c "python manage.py makemigrations &&
                 python manage.py migrate &&
                 gunicorn gerenciador_rh.wsgi:application --bind 0.0.0.0:8000"

        volumes:
            - .:/spp
        ports:
            - 8000:8000
        links:
            - "database:database"
        environment:
            - DATABASE_URL=postgresql://admin:admin@database/postgres
    database:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        ports:
            - 5433:5432
        volumes:
            - database:/var/lib/postgresql/data
volumes:
    database: