# Generated by Django 4.2.1 on 2023-05-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('logradouro', models.CharField(max_length=128)),
                ('cidade', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
    ]
